-- AlterTable
ALTER TABLE "Base" ALTER COLUMN "HP" DROP NOT NULL,
ALTER COLUMN "Attack" DROP NOT NULL,
ALTER COLUMN "Defense" DROP NOT NULL,
ALTER COLUMN "Sp_Attack" DROP NOT NULL,
ALTER COLUMN "Sp_Defense" DROP NOT NULL,
ALTER COLUMN "Speed" DROP NOT NULL;
